# Generated by Django 5.0.2 on 2024-02-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='brand',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='color',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='cost',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='currentquant',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='mouthsize',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='size',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='waterbottle',
            name='sku',
            field=models.CharField(default='default', max_length=300),
        ),
    ]
