# Generated by Django 5.0.2 on 2024-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_supplier_city_supplier_country_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbottle',
            name='suppliedby',
            field=models.CharField(default='default', max_length=300),
        ),
    ]
