# Generated by Django 5.0.2 on 2024-02-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0003_waterbottle_suppliedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbottle',
            name='suppliedby',
        ),
    ]
