# Generated by Django 5.0.2 on 2024-02-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0004_remove_waterbottle_suppliedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbottle',
            name='suppliedby',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier'),
            preserve_default=False,
        ),
    ]
