# Generated by Django 5.0.2 on 2024-02-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0005_waterbottle_suppliedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='suppliedby',
            field=models.CharField(default='default', max_length=300),
        ),
    ]
