# Generated by Django 5.0.2 on 2024-02-20 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0006_alter_waterbottle_suppliedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='suppliedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier'),
        ),
    ]
