# Generated by Django 5.0.2 on 2024-02-20 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0008_alter_waterbottle_suppliedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='currentquant',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='suppliedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier'),
        ),
    ]
